=== TypingSimulator/NarrativeSchema/narrativeStory.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "pattern": "https:\\\/\\\/raw\\.githubusercontent\\.com\\\/TypingSimulator\\\/NarrativeSchema\\\/v\\d+\\.\\d+\\.\\d+\\\/narrativeStory\\.schema\\.json"
    },
    "title": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "sections": {
      "type": "array",
      "items": {
        "properties": {
          "SectionLabel": {
            "type": "string"
          },
          "passageStrings": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^\\S(?:.*\\S)?$"
            },
            "minItems": 1
          }
        },
        "required": ["SectionLabel", "passageStrings"]
      },
      "minItems": 1
    }
  },
  "required": ["title", "author", "id", "sections", "$schema"],
  "additionalProperties": false
}

=== TypingSimulator/NarrativeSchema/NavySeal.story.json
{
  "$schema": "https://raw.githubusercontent.com/TypingSimulator/NarrativeSchema/v0.1.0/narrativeStory.schema.json",
  "title": "Navy Seal Copypasta",
  "author": "The Internet",
  "id": "navyseal",
  "sections": [
    {
      "SectionLabel": "The whole thing",
      "passageStrings": [
        "What the fuck did you just fucking say about me, you little bitch?",
        "I'll have you know I graduated top of my class in the Navy Seals",
        "and I've been involved in numerous secret raids on Al-Quaeda,",
        "and I have over 300 confirmed kills.",
        "I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces.",
        "You are nothing to me but just another target.",
        "I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words.",
        "You think you can get away with saying that shit to me over the Internet? Think again, fucker.",
        "As we speak I am contacting my secret network of spies across the USA",
        "and your IP is being traced right now so you better prepare for the storm, maggot.",
        "The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid.",
        "I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands.",
        "Not only am I extensively trained in unarmed combat,",
        "but I have access to the entire arsenal of the United States Marine Corps",
        "and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit.",
        "If only you could have known what unholy retribution your little \"clever\" comment was about to bring down upon you,",
        "maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot.",
        "I will shit fury all over you and you will drown in it. You're fucking dead, kiddo."
      ]
    }
  ]
}
